#!/bin/bash

curl -s -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --data  '{ 
   "username": "System tekniker", 
   "password": "remote110",  
   "grant_type": "password", 
   "client_id": "00aab996-6439-4f16-89b4-6c0cc851e8f3" 
  } 
 ' 'http://bullock:8080/api/v1/authorization/tokens' 






echo nice




